[template.environment]
  GQL_HOST = "WordPress URL https://www.giftsmate.net"
  NUXT_IMAGE_DOMAINS = "giftsmate.net"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://www.giftsmate.net/.*"]
